boards/urls.py
from django.urls import path
from .views import *
from .export_board import *

urlpatterns = [
        path('',BoardListView.as_view(), name='home'),
        path('topics/<int:pk>/', TopicListView.as_view(), name='board_topics'),
        path('boards/<int:pk>/new/', New_topicView.as_view(), name='new_topic' ,),
        path('boards/<int:pk>/topics/<int:topic_pk>/', PostListView.as_view(), name='topic_posts'),
        path('boards/<int:pk>/topics/<int:topic_pk>/reply/',Reply_topicView.as_view(), name='reply_topic'),
######################################################################################################################
        path('boards/<int:pk>/topics/<int:topic_pk>/posts/<int:post_pk>/', PostUpdateView.as_view(), name='edit_post'),
        path('new_articles/',new_articles,name='new_articles'),
        path('boards/fake/', generate_fake_data, name='generate_fake_data'),
                path('boards/create/',board_create, name='boards_create'),
                path('boards/<int:pk>/update/', board_update, name='boards_update'),
                path('boards/<int:pk>/delete/', board_delete, name='boards_delete'),
        path('boards/<int:pk>/to-xls/',export_boards_xls,name='to-xls'),
        path('boards/<int:pk>/to-pdf/',export_boards_pdf,name='to-pdf')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('boards.urls')),
    path('account/',include('accounts.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('oauth/', include('social_django.urls', namespace='social')), 

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from django.db.models import fields
# from django.forms.widgets import RadioSelect
# from django.http import request
from django.urls.conf import path
from .models import *
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget
from PIL import Image


class SignUpFormReader(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password=forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(required=True)
    of_age = forms.BooleanField(required=False)
    interests = forms.ModelMultipleChoiceField(queryset=Interests.objects.all(),
                                                widget=forms.CheckboxSelectMultiple,
                                                required=False
                                                )
    captcha = ReCaptchaField(widget=ReCaptchaWidget())

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label='Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['email'].label='Электороная почта'
        self.fields['confirm_password'].label='Подтвердите пароль'
        self.fields['of_age'].label = 'Есть 18?'
        self.fields['interests'].label='Интересы'

    class Meta:
            model = User
            fields=['username','email','password','confirm_password','of_age','interests','captcha']

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(f'Данный e-mail уже зарегистрован')
        return self.cleaned_data['email']


    def clean_username(self):
        username= self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Имя {username} занято')
        return username

    def clean_of_age(self):
        of_age = self.cleaned_data['of_age']
        if not of_age:
            of_age = False
        else:
            of_age = True
        return of_age

    def clean(self):
        try :
            self.cleaned_data['password'] and self.cleaned_data['confirm_password']
        except:
            raise forms.ValidationError('Введите пароль')
        password = self.cleaned_data['password']
        confirm_password= self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data

class DateInput(forms.DateInput):
    input_type = 'date'

class SignUpFormBloger(forms.ModelForm):
    STATUS_TRUE ='True'
    STATUS_FALSE='False'

    STATUS_CHOICES= (
        (STATUS_TRUE,'bloger'),
        (STATUS_FALSE,'isn`t bloger'),
    )
    
    confirm_password = forms.CharField(widget=forms.PasswordInput,required=True)
    password=forms.CharField(widget=forms.PasswordInput,required=True)
    email = forms.EmailField(required=True)
    birthday = forms.DateField(required=False, widget = DateInput())
    country = forms.CharField(max_length=50)
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(),
                                                widget=forms.CheckboxSelectMultiple,
                                                required=False
                                                )
    captcha = ReCaptchaField(widget=ReCaptchaWidget())
    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
        required=False
    )

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label='Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label='Подтвердите пароль'
        self.fields['email'].label='Электороная почта'
        self.fields['country'].label='Город'
        self.fields['birthday'].label='Дата рождения'
        self.fields['category'].label='Категории'
        self.fields['status'].label='status'


    class Meta:
        model = User
        fields = ('username','email','password','confirm_password','birthday','country','category','status','captcha')
       

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(f'Данный e-mail уже зарегистрован')
        return self.cleaned_data['email']


    def clean_username(self):
        username= self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Имя {username} занято')
        return username


    def clean(self):
        try :
            self.cleaned_data['password'] and self.cleaned_data['confirm_password']
        except:
            raise forms.ValidationError('Введите пароль')

        password = self.cleaned_data['password']
        confirm_password= self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data



class BlogerForm(forms.ModelForm):

    birthday = forms.DateField(required=False, widget = DateInput())
    category = forms.ModelMultipleChoiceField(
                                                queryset=Category.objects.all(),
                                                widget=forms.CheckboxSelectMultiple,
                                                required=False,
                                                )
    x = forms.FloatField(widget=forms.HiddenInput(),required=False)
    y = forms.FloatField(widget=forms.HiddenInput(),required=False)
    width = forms.FloatField(widget=forms.HiddenInput(),required=False)
    height = forms.FloatField(widget=forms.HiddenInput(),required=False)


        
    class Meta:
        
        model = Bloger
        fields = ['file', 'x', 'y', 'width', 'height','username','email', 'birthday', 'country','category']
        exclude = ('user','bloger','is_super',)
        widgets = {
                    'file': forms.FileInput(attrs={
                        'accept': 'image/*'
                    })
                }

    def save(self):
        photo = super(BlogerForm, self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x and y and w and h:
            image = Image.open(photo.file)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(photo.file.path)
        return photo



class ReaderForm(forms.ModelForm):
    interests = forms.ModelMultipleChoiceField(
                                                queryset=Interests.objects.all(),
                                                widget=forms.CheckboxSelectMultiple,
                                                required=False)
    x = forms.FloatField(widget=forms.HiddenInput(),required=False)
    y = forms.FloatField(widget=forms.HiddenInput(),required=False)
    width = forms.FloatField(widget=forms.HiddenInput(),required=False)
    height = forms.FloatField(widget=forms.HiddenInput(),required=False)
    class Meta:
        model = Reader
        fields = ['file', 'x', 'y', 'width', 'height','username','of_age', 'interests']
        exclude = ('user','reader','is_super',)
        widgets = {
                    'file': forms.FileInput(attrs={
                        'accept': 'image/*'
                    })
                }


    def save(self):
        photo = super(ReaderForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x and y and w and h:
            image = Image.open(photo.file)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            photo.username = self.cleaned_data.get('username')
            resized_image.save(photo.file.path)
        return photo


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    # captcha = ReCaptchaField(widget=ReCaptchaWidget())

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label='Логин или е-майл'
        self.fields['password'].label = 'Пароль'
        
    def clean(self):
        try :
            self.cleaned_data['password'] and self.cleaned_data['username']
        except:
            raise forms.ValidationError('Введите имя и пароль')
        username= self.cleaned_data['username']
        password= self.cleaned_data['password']

        if '@' in username:
            if not User.objects.filter(email=username).exists():
                raise forms.ValidationError(f'Пользователь с  почтой  {username} не найден.')
        else:
            if not User.objects.filter(username=username).exists():
                raise forms.ValidationError(f'Пользователь с логином   {username} не найден.')

        user = User.objects.filter(username=username).first()
        user1= User.objects.filter(email=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        else:
            if not user1.check_password(password):
                raise forms.ValidationError("Неверный пароль")

        return self.cleaned_data

    class Meta:
        model=User
        fields= ['username','password',]
        # 'captcha'






# class SignUpForm(UserCreationForm):
#     email = forms.CharField(max_length=254, required=False, widget=forms.EmailInput())

#     class Meta:

boards/forms.py
from django import forms
# from django.forms import fields
# from django.http import request
from .models import Post,Board
# Photo,Topic
class NewTopicForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'row':5,'placeholder':'what is your mind?'}
        ),
        max_length=4000,
        help_text='Max length is 4000')

    file = forms.FileField(required=False,widget=forms.ClearableFileInput(attrs={
        'multiple': True,
        'class':'js-upload-photos',
        'id':'fileupload',
        }))
    
    class Meta:
        fields =('subject','message','file')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = '__all__'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    {% block stylesheet %}{% endblock %} 
  </head>
  <body>
    
{%block body%}


<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          {%if not request.user.is_authenticated%}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>

          </form>
          {%else%}
          {% if avatar_image.file %}
          <li>
            <img src="{{avatar_image.file.url}}" width="40px" class="rounded-circle" >
        </li>
        {%endif%}
          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.user.username }}
          </a>
          {%endif%}
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu"{% if avatar_image.file %}style="margin-right: 300px;"{%endif%}>
            {% if request.user.username == 'admin' %}
            <a class="dropdown-item" href="/admin" >Admin panel</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            {%else%}
            <a class="dropdown-item" href="{%url 'my_account'%}">My account</a>
            <a class="dropdown-item" href="{%url 'password_change'%}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            {%endif%}
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <div class="container">
      {% if messages %}
{% for message in messages %}
{%if message.tags == 'error' %}
<div class="alert alert-danger alert-dismissible mt-5 ">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<div class="row">
  <p class="font-italic" style="font-size: 22px;">{{ message }} </p>
</div>
</div>
{%else%}
<div class="alert alert-{{message.tags}} alert-dismissible mt-5 ">
<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<div class="row">
  <p class="font-italic" style="font-size: 22px;">{{ message }}   </p>
</div>
</div>
{% endif %}

{% endfor %}

{% endif %}
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}  
  
    </div>
  </div>

    {%include 'includes/footer.html'%}

  </body>


  {%endblock body%}
 


  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/infinite.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/waypoints.min.js' %}"></script>

  <!-- <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/waypoints.min.js' %}"></script>
  <script src="{% static 'js/infinite.min.js' %}"></script> -->

  {% block javascript %}{% endblock %}

</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Django Boards</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit post{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">Edit post</li>
{% endblock %}
{% block stylesheet %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}
        
{% block javascript %}   

<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block content %}

  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}

    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{%load static%}
{% load i18n %}
{% block breadcrumb %}
<li class="breadcrumb-item active"> Boards</li>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/boards.js' %}"></script>
<script>
  var infinite = new Waypoint.Infinite({
    element: $('.infinite-container')[0],
    onBeforePageLoad: function () {
      $('.loading').show();
    },
    onAfterPageLoad: function ($items) {
      $('.loading').hide();
    }
  });
</script>
{% endblock %}


{% block content %}

<p>

{% if user.is_authenticated and bloger %}
  <button type="button"
            class="btn btn-primary js-create-board"
            data-url="{% url 'boards_create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      New board
    </button>
  </p>
  
  <button type="button" class="btn btn-primary mb-1" data-toggle="modal" data-target="#exampleModal" >
    Просмотреть последние действия
  </button>
  
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
    <div class="modal-dialog" role="document">
      <div class="modal-body p-3 mb-2 bg-white text-dark" >
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Last actions</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        
<table class="table" >
  <thead class="thead-dark">
    <tr>
      <th scope="col">User</th>
      <th scope="col">Object</th>
      <th scope="col">Changes</th>
      <th scope="col">Time</th>
    </tr>
  </thead>

  <tbody>

  {% for i in history.all%}
{%if i.history_user%}
    <tr>
    <td>{{i.history_user}}</td>
    <td>{{i.history_object}}</td>
    {%if i.history_type == '~' %}
    <td>Update</td>
    {%elif i.history_type == '+'%}
    <td>Create</td>
    {%elif i.history_type == '-'%}
    <td>Delete</td>
    {%endif%}
    <td>{{i.history_date}}</td>
    {%endif%}
    {%endfor%} 
   </tr>
  </tbody>
  </table>

</div>
</div>
</div>

{%endif%}

<table class="table infinite-container"  id="board-table">
  <thead class="thead-dark">
    <tr>
      <th>Board</th>
      <th>Posts</th>
      <th>Topics</th>
      <th>Last Post</th>
      
      {% if user.is_authenticated and bloger %}
      <th>Edit</th>
      {%endif%}

    </tr>
  </thead>
  <tbody class="infinite-item">
    
{%include 'includes/partial_board.html' %}

  </tbody>
</table>

<div class="modal fade" id="modal-board">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>

<div class="loading" style="display: none;">
  Loading...
</div>

{% if page_obj.has_next %}
<a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
{% endif %}



{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}
{% load recaptcha2 %}
{% load static %}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}

  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Django Boards</a>
    </h1>
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card">
          <div class="card-body">
            <h3 class="card-title">Log in</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}">
              {% include 'includes/form.html' %}
              {% recaptcha_init %}

              <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </form>
            <br>
            <p><strong>-- OR only for Reader Login with  --</strong></p>
            <a href="{% url 'social:begin' 'github' %}">GitHub</a> |
            <a href="{% url 'social:begin' 'facebook' %}">Facebook</a>|
            <a href="{% url 'social:begin' 'google-oauth2' %}">Google</a>

            <br>
          </div>
          <div class="card-footer text-muted text-center">
            New to Django Boards? <a href="{% url 'signup' %}">Register</a>
          </div>
        </div>
        <div class="text-center py-2">
          <small>
            <a href="{%url 'password_reset'%}" class="text-muted">Forgot your password?</a>
          </small>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/my_account.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My account{% endblock %}

{% block stylesheet %}
<link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

{% endblock %}


{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}
<div class="border border-secondary" style="padding: 8px;">

{%if avatar_image.file%}
<div class="row" style="margin-top: 20px; margin-left: 10px;">
  <img alt="Image placeholder " src="{{avatar_image.file.url}}">
<div class="col-sm-4 col-md-3">
  <img src="" class="thumbnail">
</div>
</div>
{%endif%}
  <div class="row">
    
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post"   enctype="multipart/form-data"  id="formUpload">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
    </form>

      <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Uploading foto...</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <img src="" id="image" style="max-width: 100%;">
            </div>
            <div class="modal-footer">
              <div class="btn-group pull-left" role="group">
                <button type="button" class="btn btn-default js-zoom-in">
                  <span class="glyphicon glyphicon-zoom-in">-</span>
                </button>
                <button type="button" class="btn btn-default js-zoom-out">
                  <span class="glyphicon glyphicon-zoom-out">+</span>
                </button>
              </div>
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

      {% endblock %}



 

  {% block javascript %}
  
  
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/cropper.min.js' %}"></script>

<script>
  
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
  
  {% endblock %}

templates/new_post.html
<div class="border border-secondary" style="padding: 5px;">
  <form method="post" class="mb-4">
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post a reply</button>
  </form>

</div>

templates/new_topic.html
{% extends 'base.html' %}
{% load widget_tweaks static %}
{% block javascript %}
<script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>
<script src="{% static 'js/progress-bar-upload.js' %}"></script>

{% endblock %}
{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
<li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}

<div class="border border-secondary" style="padding: 5px;">

<div  style="margin-bottom: 20px;">
<form method="POST"  enctype="multipart/form-data">

  {% csrf_token %}

  {% include 'includes/form.html' %}

  

  <!-- <button type="button" class="btn btn-primary js-upload-photos">
    <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
  </button> -->


</div>
<button type="submit" class="btn btn-success mb-5" >POST</button>
</form>
<table id="gallery" class="table table-bordered ">
  <thead>
    <tr>
      <th>Photo</th>
    </tr>
  </thead>
  <tbody>



  </tbody>
</table>

<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Uploading...</h4>
      </div>
      <div class="modal-body">
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
{% endblock %}